version: "3.9"
services:
  db:
    image: postgres:15
    container_name: los_lms_db
    environment:
      POSTGRES_USER: los
      POSTGRES_PASSWORD: los
      POSTGRES_DB: los_lms
    ports:
      - "5432:5432"
    volumes:
      - los_lms_db_data:/var/lib/postgresql/data

volumes:
  los_lms_db_data:
